nodes:
- input.visual:
    source: 0
    # Training_Data\Good_Pose\Side_View.mp4
    # Training_Data\Bad_Pose\Butt\Side_View.mp4
- model.posenet
- custom_nodes.dabble.correctMain
- draw.poses
- output.screen
